### ISSUE TITLE
Always an  error of "Unknown image format"

### ISSUE THREAD

**Issue by mingweiLIU** [syoyo/tinygltfloader#1]
I have this great tool build with a update to vs2015 while encountered some strange error: One for a memory error, another is for "Unknown image format". The test data is some files I have checked through with CesiumJS. Maybe the first one is not a common problem (the tested data is an texture embed one), while the second may be since 4 of 5 files I've test has the same problem, what I can confirm is  that the version of the tested gltf  is v1.0 and all the images are in png or jpg format.

**Comment by syoyo** [comment]
Which data(model file) gets an error for example?
