### ISSUE TITLE
Might have bug when loading glTF models with hierarchy? 

### ISSUE THREAD

**Issue by shrekshao** [syoyo/tinygltfloader#3]
Try these sample models with hierarchy: 
- https://github.com/KhronosGroup/glTF/tree/master/sampleModels/2CylinderEngine 
- https://github.com/KhronosGroup/glTF/tree/master/sampleModels/ReciprocatingSaw

I got nothing showing up on the screen for both the glview in `example` and one of my self-implemented rasterizer.

**Comment by pjcozzi** [comment]
@syoyo for context for this and #4, @shrekshao, @likangning93, and I are moving our GPU Programming and Architecture course at the University of Pennsylvania from OBJ to glTF by integrating your loader.  Any support you can offer on these issues is deeply appreciated.

**Comment by shrekshao** [comment]
Also I would be happy to fix these issues and contribute to this repo at certain time.

**Comment by syoyo** [comment]
This is not a bug. `glview`` example does not support node hierarchy yet. You can contribute!

**Comment by syoyo** [comment]
Added initial node hierarchy support in `glview` example at recent `master` and it now shows something
(I'm using scene scaling factor 0.01)

![screen shot 2016-11-24 at 6 36 28 pm](https://cloud.githubusercontent.com/assets/18676/20593266/0de1141a-b275-11e6-9177-7d06cc1097dc.png)

![screen shot 2016-11-24 at 6 35 57 pm](https://cloud.githubusercontent.com/assets/18676/20593273/151aa192-b275-11e6-921f-b311241d6aa9.png)


@shrekshao Please confirm this is an expected result.

**Comment by shrekshao** [comment]
This looks great. Thanks a lot! And really sorry about not contributing this feature in time...

Thanks to tinygltfloader, we also got something working in cuda rasterizer which is assignment for GPU programming at University of Pennslyvania. Here's screen shot of students work with multiple hierarchy glTF model. 

![](https://github.com/trungtle/Project4-CUDA-Rasterizer/raw/master/renders/videos/engine_kbuffer.gif)

![](https://github.com/trungtle/Project4-CUDA-Rasterizer/raw/master/renders/videos/engine.gif)

**Comment by syoyo** [comment]
Cool! > students work
