### ISSUE TITLE
`glview: glGetAttribLocation(progId, "in_normal")` returns -1 on Windows, VS 2013, 32bit build?

### ISSUE THREAD

**Issue by shrekshao** [syoyo/tinygltfloader#4]
I got `glGetAttribLocation(progId, "in_normal")` returns -1 on Windows, VS 2013, Win32.

After commenting this, other features seem to be correct based on the rendering results. (position, texture)

**Comment by syoyo** [comment]
`in_normal` is not used in default shader, and some OpenGL driver(probably NVIDIA?) reports `-1` if the variable is not used in the shader(variable was removed by the compiler optimization).

Do not report error for this, and add some `-1` check in recent commit. Please try the new `master`

**Comment by shrekshao** [comment]
Thanks for the explanation!
